-- ============================================================================
-- Purwakarta Wisata — Supabase Schema
-- Cara pakai: buka Supabase Dashboard > SQL Editor > paste seluruh file ini > Run.
-- Setelah tabel dibuat, isi .env dengan Project URL & anon key.
-- ============================================================================

-- ---------------------------------------------------------------------------
-- 1. TABEL destinations
-- Data lengkap per destinasi (overview, lokasi, fasilitas, harga, galeri, dll).
-- ---------------------------------------------------------------------------
create table if not exists public.destinations (
  id            uuid primary key default gen_random_uuid(),
  slug          text unique not null,               -- contoh: 'taman-batu-purwakarta'
  nama          text not null,
  kategori      text,
  kecamatan     text,
  deskripsi     text,
  alamat        text,
  latitude      double precision,                   -- koordinat pin peta
  longitude     double precision,
  harga_tiket   text,                               -- contoh: 'Rp 10.000 / orang'
  jam_operasional text,
  telepon       text,
  rating        numeric(2,1),
  ulasan        integer,
  fasilitas     jsonb default '[]'::jsonb,          -- ['Toilet','Parkir',...]
  galeri        jsonb default '[]'::jsonb,          -- ['url1','url2',...]
  maps_url      text,
  created_at    timestamptz not null default now(),
  updated_at    timestamptz not null default now()
);

-- ---------------------------------------------------------------------------
-- 2. TABEL destination_clicks
-- Dicatat tiap kali user mengklik destinasi. IP di-hash (sha256) untuk privasi.
-- ---------------------------------------------------------------------------
create table if not exists public.destination_clicks (
  id               uuid primary key default gen_random_uuid(),
  destination_id   uuid references public.destinations(id) on delete set null,
  destination_slug text,
  destination_name text,                            -- denormalisasi utk chart
  clicked_at       timestamptz not null default now(),
  visitor_id       text,                            -- session id anonim (localStorage)
  ip_hash          text,                            -- sha256(ip), bukan IP mentah
  city             text,
  country          text,
  country_code     text,
  device_type      text,                            -- mobile | tablet | desktop
  browser          text,
  os               text,
  user_agent       text,
  referrer         text,
  page_url         text
);

create index if not exists idx_clicks_dest     on public.destination_clicks (destination_slug);
create index if not exists idx_clicks_time     on public.destination_clicks (clicked_at desc);
create index if not exists idx_clicks_visitor  on public.destination_clicks (visitor_id);
create index if not exists idx_dest_slug       on public.destinations (slug);

-- ---------------------------------------------------------------------------
-- 3. ROW LEVEL SECURITY
-- anon: boleh INSERT click (dari browser) & boleh baca destinations + ringkasan.
-- Tabel clicks TIDAK bisa di-select langsung oleh anon (privasi), hanya lewat
-- fungsi ringkasan di bawah yang sudah di-agregasi.
-- ---------------------------------------------------------------------------
alter table public.destinations        enable row level security;
alter table public.destination_clicks  enable row level security;

-- ---------------------------------------------------------------------------
-- 3a. ADMIN AUTHORIZATION & AUDIT
-- Jangan pernah menaruh service_role key di frontend. Role admin disimpan
-- terpisah dari auth.users dan diverifikasi oleh database pada setiap query.
-- ---------------------------------------------------------------------------
create table if not exists public.admin_users (
  user_id       uuid primary key references auth.users(id) on delete cascade,
  role          text not null default 'admin' check (role = 'admin'),
  mfa_required  boolean not null default true,
  is_active     boolean not null default true,
  created_at    timestamptz not null default now()
);

create table if not exists public.admin_audit_logs (
  id           bigint generated by default as identity primary key,
  user_id      uuid references auth.users(id) on delete set null,
  ip_address   inet,
  user_agent   text,
  status       text not null check (status in ('success', 'failure', 'locked', 'mfa_failure')),
  created_at   timestamptz not null default now()
);

create table if not exists public.admin_login_attempts (
  key          text primary key,
  failed_count integer not null default 0,
  locked_until timestamptz,
  updated_at   timestamptz not null default now()
);

create or replace function public.is_admin()
returns boolean language sql stable security definer set search_path = public
as $$ select exists (
  select 1 from public.admin_users
  where user_id = auth.uid() and role = 'admin' and is_active = true
) $$;

-- Admin dengan MFA terverifikasi (AAL2 pada JWT). Dipakai untuk tabel sensitif:
-- sesi yang hanya login password (aal1) TIDAK lolos walau role-nya admin.
-- Catatan: policy admin_users & admin_audit_logs sengaja tetap pakai is_admin()
-- agar aplikasi bisa membaca mfa_required dan mengarahkan admin ke verifikasi MFA.
create or replace function public.is_admin_verified()
returns boolean language sql stable security definer set search_path = public
as $$ select exists (
  select 1 from public.admin_users
  where user_id = auth.uid()
    and role = 'admin'
    and is_active = true
    and coalesce(nullif(auth.jwt() ->> 'aal', ''), 'aal1') = 'aal2'
) $$;

alter table public.admin_users enable row level security;
alter table public.admin_audit_logs enable row level security;
alter table public.admin_login_attempts enable row level security;

drop policy if exists "admin can read own admin record" on public.admin_users;
create policy "admin can read own admin record" on public.admin_users
  for select using (user_id = auth.uid() and public.is_admin());

drop policy if exists "admin can read own audit logs" on public.admin_audit_logs;
create policy "admin can read own audit logs" on public.admin_audit_logs
  for select using (user_id = auth.uid() and public.is_admin());

revoke all on public.admin_login_attempts from anon, authenticated;
revoke insert, update, delete on public.admin_users from anon, authenticated;
revoke insert, update, delete on public.admin_audit_logs from anon, authenticated;

drop policy if exists "destinations public read"  on public.destinations;
drop policy if exists "destinations admin read" on public.destinations;
drop policy if exists "clicks anon insert"        on public.destination_clicks;

create policy "destinations admin read"
  on public.destinations for select
  using (public.is_admin_verified());

create policy "clicks anon insert"
  on public.destination_clicks for insert
  with check (true);

drop policy if exists "clicks admin read" on public.destination_clicks;
create policy "clicks admin read" on public.destination_clicks
  for select using (public.is_admin_verified());

-- ---------------------------------------------------------------------------
-- 4. FUNGSI ANALYTICS / EDA
-- Dipanggil oleh dashboard via RPC `get_click_eda`. Agregasi dilakukan di
-- database supaya frontend ringan & aman (RLS di-bypass oleh security definer).
-- ---------------------------------------------------------------------------
create or replace function public.get_click_eda()
returns json
language sql
security definer
set search_path = public
as $$
  with base as (
    select * from public.destination_clicks where public.is_admin_verified()
  ),
  totals as (
    select
      count(*)                                   as total_clicks,
      count(distinct visitor_id)                 as total_visitors,
      count(distinct destination_name)           as total_destinations
    from base
  ),
  daily as (
    select
      clicked_at::date as tanggal,
      count(*)         as jumlah
    from base
    group by 1
    order by 1
  ),
  growth as (
    select
      case
        when lag(total) over () is null or lag(total) over () = 0 then null
        else round(((total - lag(total) over ()) * 100.0) / lag(total) over (), 1)
      end as growth_persen
    from (
      select date_trunc('day', clicked_at)::date as hari, count(*) as total
      from base group by 1 order by 1
    ) t
    order by hari desc
    limit 1
  )
  select json_build_object(
    'total_clicks',      (select total_clicks      from totals),
    'total_visitors',    (select total_visitors    from totals),
    'total_destinations',(select total_destinations from totals),
    'growth_percent',    (select growth_persen     from growth),
    'by_destination',    (select json_agg(x) from (
                            select destination_name as nama, count(*) as klik
                            from base
                            group by destination_name
                            order by klik desc
                            limit 10
                          ) x),
    'daily_trend',       (select json_agg(x) from (
                            select tanggal, jumlah from daily
                          ) x),
    'top5',              (select json_agg(x) from (
                            select destination_name as nama, count(*) as klik
                            from base
                            group by destination_name
                            order by klik desc
                            limit 5
                          ) x),
    'by_hour',           (select json_agg(x) from (
                            select extract(hour from clicked_at)::int as jam, count(*) as jumlah
                            from base
                            group by 1 order by 1
                          ) x)
  )
$$;

revoke execute on function public.get_click_eda() from anon;
grant execute on function public.get_click_eda() to authenticated;

-- ---------------------------------------------------------------------------
-- 5. DATA VISITOR (daftar klik anonim utk tabel "siapa saja mengklik")
-- Hanya menampilkan kota/negara/device, tanpa IP mentah.
-- ---------------------------------------------------------------------------
create or replace function public.get_visitor_log(limit_n int default 200)
returns table (
  clicked_at      timestamptz,
  destination_name text,
  city            text,
  country         text,
  country_code    text,
  device_type     text,
  browser         text,
  os              text,
  referrer        text
)
language sql
security definer
set search_path = public
as $$
    select clicked_at, destination_name, city, country, country_code,
         device_type, browser, os, referrer
  from public.destination_clicks
    where public.is_admin_verified()
  order by clicked_at desc
  limit limit_n
$$;

revoke execute on function public.get_visitor_log(integer) from anon;
grant execute on function public.get_visitor_log(integer) to authenticated;

-- ---------------------------------------------------------------------------
-- 6. SEED destinations — contoh. Hapus/sesuaikan blok ini bila perlu.
-- Untuk 60+ destinasi kamu bisa generate dari file src/data/destinasi.js
-- (import lalu panggil supabase.from('destinations').upsert(...)).
-- ---------------------------------------------------------------------------
insert into public.destinations (slug, nama, kategori, kecamatan, latitude, longitude)
values
  ('taman-batu-purwakarta', 'Taman Batu Purwakarta', 'Wisata Alam', 'Bojong', -6.6336, 107.4975),
  ('waduk-jatiluhur',       'Waduk Jatiluhur',       'Danau/Waduk', 'Jatiluhur', -6.5220, 107.4070),
  ('curug-cilengkong',      'Curug Cilengkong',      'Air Terjun',  'Wanayasa', -6.7000, 107.3500),
  ('situ-buleud',           'Situ Buleud',           'Danau',       'Purwakarta', -6.5600, 107.4500)
on conflict (slug) do nothing;
